-- Attendance tracking (TNA > Attendance Management > Attendance Tracker / Reports / Compliance).
-- The MS Access instance never had these tables. Names follow what the app queries, including the
-- foreign key constraint name fk_attendance_records_status that PostgREST embeds use.

-- Global list of statuses a trainer can mark (not per project)
CREATE TABLE public.attendance_statuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_name text NOT NULL UNIQUE,
  is_present boolean NOT NULL,
  color_code text NOT NULL DEFAULT '#6c757d',
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.attendance_statuses (status_name, is_present, color_code, display_order) VALUES
  ('Present', true,  '#28a745', 1),
  ('Late',    true,  '#fd7e14', 2),
  ('Absent',  false, '#dc3545', 3),
  ('Excused', false, '#6c757d', 4);

ALTER TABLE public.attendance_statuses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Signed-in users can read attendance statuses" ON public.attendance_statuses
  FOR SELECT USING (auth.uid() IS NOT NULL);

-- One record per person per session. attendee_id is an end_users id; it deliberately has no foreign
-- key to end_users, because MS Access projects have assignments but no end_users rows.
CREATE TABLE public.attendance_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  session_id uuid NOT NULL REFERENCES public.training_sessions(id) ON DELETE CASCADE,
  attendee_id integer NOT NULL,
  attendance_status_id integer NOT NULL,
  check_in_time timestamptz,
  check_out_time timestamptz,
  actual_duration_minutes integer,
  notes text,
  marked_by uuid,
  marked_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_attendance_records_status FOREIGN KEY (attendance_status_id)
    REFERENCES public.attendance_statuses(id),
  CONSTRAINT attendance_records_session_attendee_key UNIQUE (session_id, attendee_id)
);

CREATE INDEX idx_attendance_records_project_id ON public.attendance_records(project_id);
CREATE INDEX idx_attendance_records_session_id ON public.attendance_records(session_id);
CREATE INDEX idx_attendance_records_attendee_id ON public.attendance_records(attendee_id);

CREATE TRIGGER attendance_records_updated_at
  BEFORE UPDATE ON public.attendance_records
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can view attendance for their projects" ON public.attendance_records
  FOR SELECT USING (
    project_id IN (
      SELECT pu.project_id FROM public.project_users pu
      WHERE pu.user_id = auth.uid() AND pu.is_active = true
    )
  );

CREATE POLICY "Members can record attendance for their projects" ON public.attendance_records
  FOR ALL USING (
    project_id IN (
      SELECT pu.project_id FROM public.project_users pu
      WHERE pu.user_id = auth.uid() AND pu.is_active = true AND pu.role IN ('owner', 'admin', 'member')
    )
  ) WITH CHECK (
    project_id IN (
      SELECT pu.project_id FROM public.project_users pu
      WHERE pu.user_id = auth.uid() AND pu.is_active = true AND pu.role IN ('owner', 'admin', 'member')
    )
  );
