-- =====================================================
-- MASTER SCHEMA FOR NEW SUPABASE INSTANCE
-- MS Access Integration - Individual Course Mappings
-- Created: 2025-01-17
-- =====================================================
-- This schema includes ONLY the tables needed for:
-- - MS Access data import (individual user-course mappings)
-- - TSC Wizard functionality
-- - Training schedule management
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- CORE PROJECT TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS project_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(project_id, user_id)
);

-- =====================================================
-- REFERENCE DATA TABLES
-- =====================================================

CREATE TABLE IF NOT EXISTS functional_areas (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 999,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS training_locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 999,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project_roles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 999,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE
);

-- =====================================================
-- COURSES TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS courses (
    course_id TEXT PRIMARY KEY,
    functional_area TEXT NOT NULL,
    duration_hrs NUMERIC NOT NULL,
    course_name TEXT,
    application TEXT,
    priority INTEGER NOT NULL DEFAULT 1,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE
);

-- =====================================================
-- END USERS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS end_users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    job_title TEXT,
    country TEXT,
    division TEXT,
    sub_division TEXT,
    training_location TEXT,
    project_role TEXT,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    location_name TEXT
);

-- =====================================================
-- USER COURSE MAPPINGS TABLE (Individual Assignments)
-- =====================================================

CREATE TABLE IF NOT EXISTS user_course_mappings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    end_user_id INTEGER NOT NULL REFERENCES end_users(id) ON DELETE CASCADE,
    course_id TEXT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
    assigned_by TEXT NOT NULL DEFAULT 'admin',
    assigned_date TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_course UNIQUE(end_user_id, course_id)
);

-- =====================================================
-- TRAINING SCHEDULES & SESSIONS
-- =====================================================

CREATE TABLE IF NOT EXISTS training_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    version TEXT DEFAULT to_char(now(), 'YYYYMMDDHH24MISS'),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID,
    signed_off BOOLEAN DEFAULT false,
    criteria JSONB,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS training_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    schedule_id UUID REFERENCES training_schedules(id) ON DELETE CASCADE,
    course_id TEXT NOT NULL,
    session_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    duration_hrs NUMERIC NOT NULL,
    training_location TEXT,
    max_attendees INTEGER,
    assigned_attendees INTEGER DEFAULT 0,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES training_sessions(id) ON DELETE CASCADE,
    end_user_id INTEGER NOT NULL REFERENCES end_users(id) ON DELETE CASCADE,
    course_id TEXT NOT NULL,
    assignment_status TEXT DEFAULT 'assigned',
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_session UNIQUE(session_id, end_user_id)
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- User Course Mappings indexes
CREATE INDEX IF NOT EXISTS idx_user_course_mappings_project_id
    ON user_course_mappings(project_id);
CREATE INDEX IF NOT EXISTS idx_user_course_mappings_end_user_id
    ON user_course_mappings(end_user_id);
CREATE INDEX IF NOT EXISTS idx_user_course_mappings_course_id
    ON user_course_mappings(course_id);
CREATE INDEX IF NOT EXISTS idx_user_course_mappings_project_user
    ON user_course_mappings(project_id, end_user_id);

-- End Users indexes
CREATE INDEX IF NOT EXISTS idx_end_users_project_id
    ON end_users(project_id);
CREATE INDEX IF NOT EXISTS idx_end_users_email
    ON end_users(email);

-- Courses indexes
CREATE INDEX IF NOT EXISTS idx_courses_project_id
    ON courses(project_id);
CREATE INDEX IF NOT EXISTS idx_courses_functional_area
    ON courses(functional_area);

-- Training Sessions indexes
CREATE INDEX IF NOT EXISTS idx_training_sessions_project_id
    ON training_sessions(project_id);
CREATE INDEX IF NOT EXISTS idx_training_sessions_schedule_id
    ON training_sessions(schedule_id);
CREATE INDEX IF NOT EXISTS idx_training_sessions_course_id
    ON training_sessions(course_id);

-- User Assignments indexes
CREATE INDEX IF NOT EXISTS idx_user_assignments_project_id
    ON user_assignments(project_id);
CREATE INDEX IF NOT EXISTS idx_user_assignments_session_id
    ON user_assignments(session_id);
CREATE INDEX IF NOT EXISTS idx_user_assignments_user_id
    ON user_assignments(end_user_id);

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE functional_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE end_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_course_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_assignments ENABLE ROW LEVEL SECURITY;

-- Projects policies
CREATE POLICY "Users can view their projects" ON projects
    FOR SELECT USING (
        id IN (
            SELECT project_id FROM project_users
            WHERE user_id = auth.uid() AND is_active = true
        )
    );

-- Project Users policies
CREATE POLICY "Users can view project members" ON project_users
    FOR SELECT USING (
        project_id IN (
            SELECT project_id FROM project_users
            WHERE user_id = auth.uid() AND is_active = true
        )
    );

-- Generic project-based SELECT policy for reference data and main tables
CREATE POLICY "Users can view data for their projects" ON functional_areas
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON training_locations
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON project_roles
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON courses
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON end_users
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view mappings for their projects" ON user_course_mappings
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON training_schedules
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON training_sessions
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

CREATE POLICY "Users can view data for their projects" ON user_assignments
    FOR SELECT USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
        )
    );

-- INSERT/UPDATE/DELETE policies for user_course_mappings
CREATE POLICY "Users can insert mappings for their projects" ON user_course_mappings
    FOR INSERT WITH CHECK (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
            AND pu.role IN ('owner', 'admin', 'member')
        )
    );

CREATE POLICY "Users can update mappings for their projects" ON user_course_mappings
    FOR UPDATE USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
            AND pu.role IN ('owner', 'admin', 'member')
        )
    );

CREATE POLICY "Users can delete mappings for their projects" ON user_course_mappings
    FOR DELETE USING (
        project_id IN (
            SELECT pu.project_id FROM project_users pu
            WHERE pu.user_id = auth.uid() AND pu.is_active = true
            AND pu.role IN ('owner', 'admin', 'member')
        )
    );

-- =====================================================
-- TRIGGERS
-- =====================================================

-- Updated timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to relevant tables
CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_functional_areas_updated_at
    BEFORE UPDATE ON functional_areas
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_training_locations_updated_at
    BEFORE UPDATE ON training_locations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_project_roles_updated_at
    BEFORE UPDATE ON project_roles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER user_course_mappings_updated_at
    BEFORE UPDATE ON user_course_mappings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

-- Get all courses assigned to a user
CREATE OR REPLACE FUNCTION get_user_courses(p_end_user_id INTEGER)
RETURNS TABLE (
    course_id TEXT,
    course_name TEXT,
    functional_area TEXT,
    duration_hrs NUMERIC,
    assigned_by TEXT,
    assigned_date TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.course_id,
        c.course_name,
        c.functional_area,
        c.duration_hrs,
        ucm.assigned_by,
        ucm.assigned_date
    FROM user_course_mappings ucm
    JOIN courses c ON ucm.course_id = c.course_id
    WHERE ucm.end_user_id = p_end_user_id
    ORDER BY c.course_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get all users assigned to a course
CREATE OR REPLACE FUNCTION get_course_users(p_course_id TEXT, p_project_id UUID)
RETURNS TABLE (
    end_user_id INTEGER,
    name TEXT,
    email TEXT,
    project_role TEXT,
    training_location TEXT,
    assigned_by TEXT,
    assigned_date TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        eu.id,
        eu.name,
        eu.email,
        eu.project_role,
        eu.training_location,
        ucm.assigned_by,
        ucm.assigned_date
    FROM user_course_mappings ucm
    JOIN end_users eu ON ucm.end_user_id = eu.id
    WHERE ucm.course_id = p_course_id
        AND ucm.project_id = p_project_id
    ORDER BY eu.name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bulk assign courses to users
CREATE OR REPLACE FUNCTION bulk_assign_courses(
    p_project_id UUID,
    p_user_ids INTEGER[],
    p_course_ids TEXT[],
    p_assigned_by TEXT DEFAULT 'bulk',
    p_replace_mode BOOLEAN DEFAULT false
)
RETURNS INTEGER AS $$
DECLARE
    v_user_id INTEGER;
    v_course_id TEXT;
    v_count INTEGER := 0;
BEGIN
    -- If replace mode, delete existing assignments for these users
    IF p_replace_mode THEN
        DELETE FROM user_course_mappings
        WHERE end_user_id = ANY(p_user_ids)
            AND project_id = p_project_id;
    END IF;

    -- Insert new assignments
    FOREACH v_user_id IN ARRAY p_user_ids
    LOOP
        FOREACH v_course_id IN ARRAY p_course_ids
        LOOP
            INSERT INTO user_course_mappings (
                project_id,
                end_user_id,
                course_id,
                assigned_by,
                assigned_date
            ) VALUES (
                p_project_id,
                v_user_id,
                v_course_id,
                p_assigned_by,
                NOW()
            )
            ON CONFLICT (end_user_id, course_id) DO NOTHING;

            IF FOUND THEN
                v_count := v_count + 1;
            END IF;
        END LOOP;
    END LOOP;

    RETURN v_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- PERMISSIONS
-- =====================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- =====================================================
-- VERIFICATION QUERIES (for testing after deployment)
-- =====================================================

-- Uncomment these to verify the schema after deployment:

-- Check all tables created
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' ORDER BY table_name;

-- Check RLS is enabled
-- SELECT tablename, rowsecurity FROM pg_tables
-- WHERE schemaname = 'public' ORDER BY tablename;

-- Check indexes
-- SELECT indexname, tablename FROM pg_indexes
-- WHERE schemaname = 'public' ORDER BY tablename, indexname;

-- =====================================================
-- END OF MASTER SCHEMA
-- =====================================================
