-- =====================================================
-- AUTHENTICATION SCHEMA FOR NEW SUPABASE INSTANCE
-- Custom authentication system built on Supabase Auth
-- Created: 2025-01-17
-- =====================================================
-- This schema includes the auth tables needed for:
-- - User authentication and authorization
-- - Role-based access control
-- - Login audit and security features
-- =====================================================

-- Enable UUID extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- AUTHENTICATION TABLES
-- =====================================================

-- Main users table (extends Supabase auth.users)
CREATE TABLE IF NOT EXISTS auth_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    user_type TEXT DEFAULT 'standard',
    is_super_admin BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Roles table
CREATE TABLE IF NOT EXISTS auth_roles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Permissions table
CREATE TABLE IF NOT EXISTS auth_permissions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    resource TEXT NOT NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User roles mapping
CREATE TABLE IF NOT EXISTS auth_user_roles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES auth_roles(id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    assigned_by UUID REFERENCES auth_users(id),
    UNIQUE(user_id, role_id)
);

-- Role permissions mapping
CREATE TABLE IF NOT EXISTS auth_role_permissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role_id INTEGER NOT NULL REFERENCES auth_roles(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES auth_permissions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(role_id, permission_id)
);

-- Login audit log
CREATE TABLE IF NOT EXISTS auth_login_audit (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth_users(id) ON DELETE SET NULL,
    email TEXT,
    success BOOLEAN NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    failure_reason TEXT,
    attempted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Password history (for preventing reuse)
CREATE TABLE IF NOT EXISTS auth_password_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Rate limiting for login attempts
CREATE TABLE IF NOT EXISTS auth_rate_limiting (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    identifier TEXT NOT NULL, -- email or IP address
    attempt_count INTEGER DEFAULT 1,
    first_attempt_at TIMESTAMPTZ DEFAULT NOW(),
    last_attempt_at TIMESTAMPTZ DEFAULT NOW(),
    blocked_until TIMESTAMPTZ,
    UNIQUE(identifier)
);

-- Two-factor authentication
CREATE TABLE IF NOT EXISTS auth_two_factor_auth (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID UNIQUE NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    secret TEXT NOT NULL,
    enabled BOOLEAN DEFAULT false,
    backup_codes TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Email verification tokens
CREATE TABLE IF NOT EXISTS auth_email_verification_tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User sessions
CREATE TABLE IF NOT EXISTS auth_user_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    session_token TEXT UNIQUE NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_activity_at TIMESTAMPTZ DEFAULT NOW()
);

-- User functional areas (for project-based access)
CREATE TABLE IF NOT EXISTS auth_user_functional_areas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    functional_area_id INTEGER REFERENCES functional_areas(id) ON DELETE CASCADE,
    can_view BOOLEAN DEFAULT true,
    can_edit BOOLEAN DEFAULT false,
    can_delete BOOLEAN DEFAULT false,
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    assigned_by UUID REFERENCES auth_users(id),
    UNIQUE(user_id, functional_area_id)
);

-- User permissions (resource-level access control)
CREATE TABLE IF NOT EXISTS auth_user_permissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL, -- 'users', 'assignments', 'schedules', etc.
    can_view BOOLEAN DEFAULT true,
    can_edit BOOLEAN DEFAULT false,
    can_delete BOOLEAN DEFAULT false,
    can_export BOOLEAN DEFAULT false,
    functional_area_names TEXT[], -- Array of allowed functional area names
    training_location_names TEXT[], -- Array of allowed training location names
    project_ids UUID[], -- Array of allowed project IDs
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, resource_type)
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_auth_users_email ON auth_users(email);
CREATE INDEX IF NOT EXISTS idx_auth_users_is_active ON auth_users(is_active);

CREATE INDEX IF NOT EXISTS idx_auth_user_roles_user_id ON auth_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_roles_role_id ON auth_user_roles(role_id);

CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_role_id ON auth_role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_auth_role_permissions_permission_id ON auth_role_permissions(permission_id);

CREATE INDEX IF NOT EXISTS idx_auth_login_audit_user_id ON auth_login_audit(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_login_audit_attempted_at ON auth_login_audit(attempted_at);
CREATE INDEX IF NOT EXISTS idx_auth_login_audit_success ON auth_login_audit(success);

CREATE INDEX IF NOT EXISTS idx_auth_password_history_user_id ON auth_password_history(user_id);

CREATE INDEX IF NOT EXISTS idx_auth_rate_limiting_identifier ON auth_rate_limiting(identifier);

CREATE INDEX IF NOT EXISTS idx_auth_user_sessions_user_id ON auth_user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_sessions_session_token ON auth_user_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_auth_user_sessions_expires_at ON auth_user_sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_auth_user_functional_areas_user_id ON auth_user_functional_areas(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_functional_areas_functional_area_id ON auth_user_functional_areas(functional_area_id);

CREATE INDEX IF NOT EXISTS idx_auth_user_permissions_user_id ON auth_user_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_permissions_resource_type ON auth_user_permissions(resource_type);

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all auth tables
ALTER TABLE auth_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_login_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_password_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_rate_limiting ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_two_factor_auth ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_email_verification_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_user_functional_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_user_permissions ENABLE ROW LEVEL SECURITY;

-- Auth users policies
CREATE POLICY "Users can view their own profile" ON auth_users
    FOR SELECT USING (id = auth.uid());

CREATE POLICY "Users can update their own profile" ON auth_users
    FOR UPDATE USING (id = auth.uid());

-- Auth roles policies (read-only for authenticated users)
CREATE POLICY "Authenticated users can view roles" ON auth_roles
    FOR SELECT USING (auth.uid() IS NOT NULL);

-- Auth permissions policies (read-only for authenticated users)
CREATE POLICY "Authenticated users can view permissions" ON auth_permissions
    FOR SELECT USING (auth.uid() IS NOT NULL);

-- Auth user roles policies
CREATE POLICY "Users can view their own roles" ON auth_user_roles
    FOR SELECT USING (user_id = auth.uid());

-- Auth role permissions policies (read-only for authenticated users)
CREATE POLICY "Authenticated users can view role permissions" ON auth_role_permissions
    FOR SELECT USING (auth.uid() IS NOT NULL);

-- Auth login audit policies
CREATE POLICY "Users can view their own login audit" ON auth_login_audit
    FOR SELECT USING (user_id = auth.uid());

-- Auth password history policies (view own only)
CREATE POLICY "Users can view their own password history" ON auth_password_history
    FOR SELECT USING (user_id = auth.uid());

-- Auth two-factor auth policies
CREATE POLICY "Users can view their own 2FA settings" ON auth_two_factor_auth
    FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can update their own 2FA settings" ON auth_two_factor_auth
    FOR UPDATE USING (user_id = auth.uid());

-- Auth user sessions policies
CREATE POLICY "Users can view their own sessions" ON auth_user_sessions
    FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can delete their own sessions" ON auth_user_sessions
    FOR DELETE USING (user_id = auth.uid());

-- Auth user functional areas policies
CREATE POLICY "Users can view their own functional areas" ON auth_user_functional_areas
    FOR SELECT USING (user_id = auth.uid());

-- Auth user permissions policies
CREATE POLICY "Users can view their own permissions" ON auth_user_permissions
    FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can update their own permissions" ON auth_user_permissions
    FOR UPDATE USING (user_id = auth.uid());

-- =====================================================
-- TRIGGERS
-- =====================================================

-- Updated timestamp trigger function (reuse from main schema if exists)
CREATE OR REPLACE FUNCTION update_auth_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to relevant tables
CREATE TRIGGER update_auth_users_updated_at
    BEFORE UPDATE ON auth_users
    FOR EACH ROW EXECUTE FUNCTION update_auth_updated_at_column();

CREATE TRIGGER update_auth_roles_updated_at
    BEFORE UPDATE ON auth_roles
    FOR EACH ROW EXECUTE FUNCTION update_auth_updated_at_column();

CREATE TRIGGER update_auth_two_factor_auth_updated_at
    BEFORE UPDATE ON auth_two_factor_auth
    FOR EACH ROW EXECUTE FUNCTION update_auth_updated_at_column();

-- =====================================================
-- DEFAULT DATA
-- =====================================================

-- Insert default roles
INSERT INTO auth_roles (name, description) VALUES
    ('super_admin', 'Full system access and control'),
    ('admin', 'Project administration and management'),
    ('manager', 'Team and training management'),
    ('member', 'Standard user access'),
    ('viewer', 'Read-only access')
ON CONFLICT (name) DO NOTHING;

-- Insert default permissions
INSERT INTO auth_permissions (name, description, resource, action) VALUES
    ('projects.view', 'View projects', 'projects', 'view'),
    ('projects.create', 'Create projects', 'projects', 'create'),
    ('projects.edit', 'Edit projects', 'projects', 'edit'),
    ('projects.delete', 'Delete projects', 'projects', 'delete'),
    ('users.view', 'View users', 'users', 'view'),
    ('users.create', 'Create users', 'users', 'create'),
    ('users.edit', 'Edit users', 'users', 'edit'),
    ('users.delete', 'Delete users', 'users', 'delete'),
    ('training.view', 'View training data', 'training', 'view'),
    ('training.create', 'Create training schedules', 'training', 'create'),
    ('training.edit', 'Edit training schedules', 'training', 'edit'),
    ('training.delete', 'Delete training schedules', 'training', 'delete')
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- PERMISSIONS
-- =====================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- =====================================================
-- END OF AUTHENTICATION SCHEMA
-- =====================================================
